version: 2

  workflows:
    version: 2
    build:
      jobs:
        - build
        - deploy

  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:15:84:fe:ff:40:c2:7a:2e:80:4d:79:d7:92:e6:74"
      - checkout
      - restore_cache:
          keys:
          - dependencies-
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Gatsby build site
          command: yarn build

  docs-deploy:
    docker:
      - image: node:latest
    steps:
      - checkout
      - attach_workspace:
          at: /
      - run:
          name: Install and configure dependencies
          command: |
            yarn global add gh-pages@2.0.1
            git config user.email "ci-build@klukas.net"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "bc:15:84:fe:ff:40:c2:7a:2e:80:4d:79:d7:92:e6:74"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] Updates" --dist public
