name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn build
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.deploy_host }}
        key: ${{ secrets.ssh_privatekey }}
        username: ${{ secrets.deploy_user }}
        port: ${{ secrets.deploy_port }}
        source: "dist/"
        rm: true
        target: "/home/${{ secrets.deploy_user }}/public_html"
