name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn build
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.0.8
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.ssh_privatekey }}
        # Remote host
        REMOTE_HOST: ${{ secrets.deploy_host }}
        # Remote user
        REMOTE_USER: ${{ secrets.deploy_user }}
        # Remote port
        REMOTE_PORT: ${{ secrets.deploy_port }}
        # Source directory
        SOURCE: dist/# optional, default is 
        # Target directory
        TARGET: /home/${{ secrets.deploy_user }}/public_html
