name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn build
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - uses: actions/checkout@master
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        # Path to the local folder you want to copy.
        local: 'dist/'
        # Path on the remote server to copy to.
        remote: ${{ secrets.deploy_path }}
        # Hostname or IP address of the server.
        host: ${{ secrets.deploy_host }} # optional, default is localhost
        # Username for authentication.
        username: ${{ secrets.deploy_user }} # optional
        # Port number of the server.
        port: ${{ secrets.deploy_port }} # optional, default is 22
        # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        privateKey: ${{ secrets.ssh_privatekey }} # optional

